version: '3.8'

services:
  cassandra-spring-boot:
    image: cassandra:latest
    container_name: cassandra-spring-boot
    ports:
      - "9042:9042"
    networks:
      - elastic
    deploy:
      restart_policy:
        condition: on-failure

  some-mysql:
    image: mysql:latest
    container_name: some-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - elastic
    deploy:
      restart_policy:
        condition: on-failure

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"  # Corrected port
    mem_limit: 2GB
#    deploy:
#      restart_policy:
#        condition: on-failure

  es02:
#    depends_on:
#      - es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    networks:
      - elastic
    ports:
      - "9301:9200"  # Corrected port
      - "9302:9300"  # Corrected port
    mem_limit: 2GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    deploy:
#      restart_policy:
#        condition: on-failure

  es03:
#    depends_on:
#      - es02
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    networks:
      - elastic
    ports:
      - "9400:9200"
      - "9401:9300"  # Corrected port
    mem_limit: 2GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      restart_policy:
        condition: on-failure

networks:
  elastic: